version: '3.4'
networks:
    airflow_network_v2:
        driver: bridge
services:
    airflow_scheduler_v2:
        image: apache/airflow:2.2.2
        env_file:
                - /home/igf/airflow_v2/secrets/airflow_env
        user: "${AIRFLOW_UID:-50000}:0"
        volumes:
                - /home/igf/airflow_v2/logs:/rds/general/user/igf/ephemeral/airflow_v2_logs/logs:rw
                - /home/igf/airflow_v2/github/igf-airflow-hpc:/rds/general/user/igf/home/data2/airflow_v2/github/igf-airflow-hpc:ro
                - /home/igf/airflow_v2/github/data-management-python:/rds/general/user/igf/home/data2/airflow_v2/github/data-management-python:ro
                - /home/igf/airflow_v2/secrets:/rds/general/user/igf/home/data2/airflow_v2/secrets:ro
                - /home/igf/airflow_v2/plugin:/rds/general/user/igf/home/data2/airflow_v2/plugin:ro
        restart: always
        command: scheduler
        container_name: airflow_scheduler_v2
        networks:
               - airflow_network_v2
    airflow_worker_v2:
        image: apache/airflow:2.2.2
        env_file:
                - /home/igf/airflow_v2/secrets/airflow_env
        links:
                - airflow_scheduler_v2
        depends_on:
                - airflow_scheduler_v2
        user: "${AIRFLOW_UID:-50000}:0"
        ports:
                - "8794:8794"
        volumes:
                - /home/igf/airflow_v2/logs:/rds/general/user/igf/ephemeral/airflow_v2_logs/logs:rw
                - /home/igf/airflow_v2/github/igf-airflow-hpc:/rds/general/user/igf/home/data2/airflow_v2/github/igf-airflow-hpc:ro
                - /home/igf/airflow_v2/github/data-management-python:/rds/general/user/igf/home/data2/airflow_v2/github/data-management-python:ro
                - /home/igf/airflow_v2/secrets:/rds/general/user/igf/home/data2/airflow_v2/secrets:ro
                - /home/igf/airflow_v2/plugin:/rds/general/user/igf/home/data2/airflow_v2/plugin:ro
        restart: always
        celery worker -q generic --celery-hostname wells
        container_name: airflow_worker_v2
        networks:
               - airflow_network_v2