version: '3.9'
networks:
    airflow_network_v3:
        driver: bridge
services:
    airflow_scheduler_v3:
        image: airflow:v2.6.2
        env_file:
            - /home/igf/airflow_v3/secrets/airflow_env
        logging:
            driver: "json-file"
            options:
                max-size: "2048m"
        user: "${AIRFLOW_UID:-50000}:${GID}"
        volumes:
            - /home/igf/airflow_v3/airflow_v3_logs:/rds/general/user/igf/ephemeral/airflow_v3_logs:rw
            - /home/igf/airflow_v3/github/igf-airflow-hpc:/rds/general/user/igf/home/data2/airflow_v3/github/igf-airflow-hpc:ro
            - /home/igf/airflow_v3/github/data-management-python:/rds/general/user/igf/home/data2/airflow_v3/github/data-management-python:ro
            - /home/igf/airflow_v3/secrets:/rds/general/user/igf/home/data2/airflow_v3/secrets:ro
            - /home/igf/airflow_v3/plugin:/rds/general/user/igf/home/data2/airflow_v3/plugin:ro
        restart: unless-stopped
        command: scheduler
        container_name: airflow_scheduler_v3
        networks:
            - airflow_network_v3
    airflow_worker_v3:
        image: airflow:v2.6.2
        env_file:
            - /home/igf/airflow_v3/secrets/airflow_env
        logging:
            driver: "json-file"
            options:
                max-size: "2048m"
        links:
            - airflow_scheduler_v3
        depends_on:
            airflow_scheduler_v3:
                condition: service_started
        user: "${AIRFLOW_UID:-50000}:${GID}"
        volumes:
            - /home/igf/airflow_v3/airflow_v3_logs:/rds/general/user/igf/ephemeral/airflow_v3_logs:rw
            - /home/igf/airflow_v3/github/igf-airflow-hpc:/rds/general/user/igf/home/data2/airflow_v3/github/igf-airflow-hpc:ro
            - /home/igf/airflow_v3/github/data-management-python:/rds/general/user/igf/home/data2/airflow_v3/github/data-management-python:ro
            - /home/igf/airflow_v3/secrets:/rds/general/user/igf/home/data2/airflow_v3/secrets:ro
            - /home/igf/airflow_v3/plugin:/rds/general/user/igf/home/data2/airflow_v3/plugin:ro
            - /home/igf/.ssh/id_rsa:/SSH/id_rsa:ro
        restart: unless-stopped
        ports:
            - "8793:8793"
        command: celery worker -q generic --celery-hostname wells
        container_name: airflow_worker_v3
        networks:
            - airflow_network_v3